# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kindle Display add-on
version: "1.0.0"
slug: kindle-display
description: Kindle Display add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello Kindle Display..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-kindle-display"
